Layout/LineLength:
  Enabled: false
# https://stackoverflow.com/questions/30932732/what-is-meant-by-assignment-branch-condition-size-too-high-and-how-to-fix-it
Metrics/AbcSize:
  Max: 25
# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/MethodLength:
  Max: 25
AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: disable
  Exclude:
    - 'bin/**/*'
