version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.7.2
    resource_class: small
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-2.6.0-{{ checksum "testzone.gemspec" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-2.6.0-{{ checksum "testzone.gemspec" }}

      - run:
          name: Run Rubocop
          command: |
            bundle exec rubocop --fail-level C

      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress  --format RspecJunitFormatter  --out /tmp/test-results/rspec.xml  --format progress $TEST_FILES

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  build:
    jobs:
      - build
